Exclude files from index according to files.exclude
felixfbecker/vscode-php-intellisense pull request #437
Opened 2019-07-30 22:50 UTC by joas8211

Pass exclude patterns in initialization options. This is one way, but there could be other ways for implementing this.

Requires support from the language server (felixfbecker/php-language-server#749).

2019-08-07 12:57 UTC, felixfbecker requested changes
Hey @joas8211, `initializationOptions` should not be used for user configuration per the spec: https://github.com/microsoft/language-server-protocol/commit/545cd6958ace603cd254e8e376e4fb2840bb1223

2019-08-07 14:18 UTC, joas8211 commented
So should indexing be done outside of initialization then? `workspace/configuration` is not allowed during initialize-request.

> Until the server has responded to the initialize request with an InitializeResult, the client must not send any additional requests or notifications to the server. In addition the server is not allowed to send any requests or notifications to the client until it has responded with an InitializeResult, with the exception that during the initialize request the server is allowed to send the notifications window/showMessage, window/logMessage and telemetry/event as well as the window/showMessageRequest request to the client.
\- [LSP specification](https://microsoft.github.io/language-server-protocol/specification#initialize)

There has been some conversation on when and how indexing should happen (microsoft/language-server-protocol#54), but there's no conclusion on suggested method. Although `initializationOptions` was considered for indexing related configuration (eg. include / exclude) by protocol author @kaloyan-raev in [a comment](https://github.com/Microsoft/language-server-protocol/issues/54#issuecomment-246364335).

> Let's take as example the question "When the language server should start indexing the project?". A possible answer is "The indexing should be triggered when the client sends the initialize request.". So far so good. It still needs to be documented, so all clients and servers know this is the way to do it.
>
> But, what if the client needs to send the server some configuration related to the indexing. For example, some clients may want to include/exclude some folders from the indexer. The didChangeConfiguration notification goes after the initialize request, which is late (the indexing is already going). VSCode has an additional initializationOptions as part of InitializeParams, but it is not documented in the protocol. See #55.

2019-08-07 14:23 UTC, joas8211 commented
One way is to wait for the initialization before requesting exclude settings and doing indexing.

2019-08-07 14:24 UTC, felixfbecker commented
Indexing is **already** done asynchronously after `initialize` already returned a response:

https://github.com/felixfbecker/php-language-server/blob/9dc16565922ae1fcf18a69b15b3cd15152ea21e6/src/LanguageServer.php#L239

Note there is no `yield`, this triggers the method to run in the background and crash the server if an error happens.

2019-08-07 15:39 UTC, joas8211 commented
I see. I'll just implement `workspace/configuration` request on the language server and use it to get excludes when indexing.

This PR might not be needed but I'll keep it open until I make the changes.

2019-10-12 15:19 UTC, gnoe commented
Is it possible to send the exclude patterns in the command executed by the vscode-php-intellisense like:

--- extension -----------------------------------
const childProcess = spawn(executablePath, [
                    context.asAbsolutePath(
                        path.join('..', 'php-language-server', 'bin', 'php-language-server.php')
                    ),
                    '--tcp=127.0.0.1:' + server.address().port,
                    '--memory-limit=' + memoryLimit,
                    '--exclude=' + exclude.join(','),
                ])

--- server --------------------------------------------
and then in LanguageServer::initialize

$config = \getopt('', ['exclude::']);
$config['root'] = $rootPath; // necesary to resolve full path of the glob patterns
$configuration = new Configuration($config); 

--- indexing with exclude patterns ------------------
For the indexing part, I think it would be better to use the same approach of the  Webmozart\Glob\Iterator\GlobFilterIterator where the constructor resolves the regex of glob patterns to exclude and then do a preg_match in the accept method, instead of doing a Glob::match() in every iteration.

FileSystemFilesFinder::find(string $glob, array $exclude= [])

$iterator = new GlobIterator($glob);
if ($exclude) {
    $iterator = new ExcludeGlobFilterIterator($exclude, $iterator);
}

2019-11-29 13:12 UTC, magarrent approved these changes

2025-09-08 06:24 UTC, closed without merging